### ISSUE TITLE
successOrNext is undefined

### ISSUE THREAD

**Issue by DPr00f** [havard/node-openid#127]
There's an error on version 0.12 of node (Tested on Ubuntu) that says that successOrNext is undefined.
I've managed to fix it, going to create a pull request in the next minutes.

**Comment by havard** [comment]
Thanks for reporting. Let me see if I can reproduce. 

Which version does this happen on? Have you tested the version before to determine if there is a regression?

**Comment by DPr00f** [comment]
Happened on node v0.12.0 I could easily reproduce it. With version 0.10.25 and 0.10.27 works fine.

**Comment by havard** [comment]
Sorry, ambiguous question, I was asking which versions of node-openid you have tested.

**Comment by DPr00f** [comment]
No I haven't test other node-openid versions. If you can't until later on today I will do it.

**Comment by havard** [comment]
Which version have you tested? 0.5.10?

**Comment by DPr00f** [comment]
Yeah 0.5.10. I used passport-openid, and I was trying to reach the steam openid service. Don't have the urls here. Are you having trouble reproducing it?

**Comment by havard** [comment]
Yes. Could you try downgrading to 0.5.9 and see if you get the same behavior?

**Comment by havard** [comment]
Logging in to Steam using 0.5.10 on Node 0.10 and 0.12 works fine for me (given I provide a realm, and use stateless mode (Steam does not support association)).

**Comment by DPr00f** [comment]
Sorry I wasn't available yesterday. I'll show you an example tonight that breaks and I'll downgrade as well to see if it matters.

**Comment by DPr00f** [comment]
Thing is, I'm not even sure if it's a problem with node-openid or nodejs itself.

**Comment by havard** [comment]
Me neither, so a way to reproduce would be great.

**Comment by DPr00f** [comment]
Give me one hour to set something up

**Comment by DPr00f** [comment]
Kay https://github.com/DPr00f/node-openid-error
Found the problem.
node-jsx is causing the exception. Just on node 0.12, not on node 0.10.
if you comment the first line on helpers/globals.js it will work on 0.12, else, it will fail

**Comment by havard** [comment]
Interesting find, thanks, I will review it.

**Comment by havard** [comment]
Just pushed 0.5.11, can you test?

**Comment by DPr00f** [comment]
Well done. It works. Close the PR I've made then.

**Comment by havard** [comment]
Thanks for reporting and helping out reproducing and testing!
