### ISSUE TITLE
Storing association state

### ISSUE THREAD

**Issue by ChongYunPeng** [havard/node-openid#133]
Hi I'm really new to this package and I would like to find out if there are any examples where these two functions are used.
1. saveAssociation(provider, type, handle, secret, expiry_time_in_seconds, callback)
2. loadAssociation(handle, callback)

**Comment by havard** [comment]
Sure, see https://github.com/havard/node-openid/blob/master/openid.js#L94 for a simple `saveAssociation` and https://github.com/havard/node-openid/blob/master/openid.js#L103 for a simple `loadAssociation`.
