### ISSUE TITLE
is possible to integrate openid with hapijs? and also make it work with steampowered.com?

### ISSUE THREAD

**Issue by unutoiul** [havard/node-openid#139]
I'm looking for a solution of how to integrate steampowered.com with Hapi JS and I couldn't find anything out there..

Thanks,
Lucas

**Comment by havard** [comment]
It seems hapijs does not support OpenID. You'll have to try and convince them or contribute support, there's an [open issue on their side](https://github.com/hapijs/bell/issues/164) which I see you've already found. :)
