### ISSUE TITLE
Port to TypeScript

### ISSUE THREAD

**Issue by cprecioso** [havard/node-openid#143]
Hi, I've been doing some work on node-openid, porting it to [TypeScript](http://www.typescriptlang.org) just as a hobby, but that has left me with a more consistent (in terms of coding style, idioms and formatting) library, and the strong typing has made it less prone to a whole host of errors and typos.

I haven't changed the API at all, neither internal nor external; though the `base64` script has been removed in favor of using `Buffer` which is built-in and gives use these facilites. Also, it has been somewhat updated to ES6 (mostly the module API), though TypeScript compiles it down to ES5.

I have also added dependencies to `npm` versions of built-in packages, as to have a versioned API to interface with, and not depend on the `node` version being used.

At this time, I feel comfortable asking for it to be merged upstream (it does pass `npm test`). I realize this would mean for the library to change language (though a very similar superset of JS that compiles down to it; and maintaining the exact same API), but I think this could be considered, as to create more stable code and reduce errors.

In the case this couldn't be acceptable, maybe the compiled JS could be the thing merged upstream with a few fixes, not with many changes as basically all the compiler does is to check types, strip the type annotations and compile some ES6 back to ES5.

How does the maintainers see this? You can see my progress at [the `typescript` branch of my fork](https://github.com/cprecioso/node-openid/tree/typescript). Would any more work be required before being merged? I'd be willing to do it, as well as answering any questions or concerns you may have.

**Comment by havard** [comment]
I fail to see what we gain here. The arguments you give are either generic for any TypeScript work, or not related to TypeScript. What's the real gain for node-openid that makes this worthwhile?

**Comment by havard** [comment]
No response, closing.
