### ISSUE TITLE
Connecting to local Identity Provider

### ISSUE THREAD

**Issue by wjagodfrey** [havard/node-openid#147]
Hi, I'm unable to connect to an OIDC Identity Provider I have running on my machine. This may be down to my own incompetence.

It's likely that I'm missing something, but I've looked through the readme, examples and source code and can't see an easy way of pointing this at a specific provider. I've tried passing the provider url as the `openid_identifier` and that throws:

```
Authentication failed: No providers found for the given identifier
```

The `openid_identifier` seems to be the only documented parameter for provider discovery.

For instance, I'm using a well-known test OIDC provider for the Ruby `openid_connect` library: http://connect-op.herokuapp.com

If I connect to it from the library's own [RP example](connect-rp.herokuapp.com), it works. It doesn't work if I connect to it from `havard/node-openid`, with `connect-op.herokuapp.com` as the `openid_identifier`.

Any ideas?

**Comment by wjagodfrey** [comment]
For instance, I'm using a well-known test OIDC provider for the Ruby `openid_connect` library: http://connect-op.herokuapp.com

If I connect to it from the library's own [RP example](connect-rp.herokuapp.com), it works. It doesn't work if I connect to it from `havard/node-openid`, with `connect-op.herokuapp.com` as the `openid_identifier`.

**Comment by havard** [comment]
This library supports OpenID 2.0, and not OpenID Connect. The latter is based on OAuth 2.0.
