### ISSUE TITLE
http proxy support

### ISSUE THREAD

**Issue by rzk** [havard/node-openid#151]
Hello, does current version of node-openid support HTTP_PROXY_HOST/HTTP_PROXY_PORT as readme states?

I can't find any usages of HTTP(S)_PROXY_* in openid.js, while in previous issues/PRs and versions around 2013, it actually been used.

How do I use node-openid behind HTTP proxy?

**Comment by havard** [comment]
This is supported through the use of the request module, see [here](https://github.com/request/request/blob/master/README.md#proxies).
