### ISSUE TITLE
Invalid assertion response from provider / No providers found for the given identifier

### ISSUE THREAD

**Issue by notJackson** [havard/node-openid#153]
Logging into the site works most of the time. However there are periods, which usually last about 30 mins, where logging in simply is not possible.

Reponses:

```
{ message: 'Invalid assertion response from provider' }
{ message: 'No providers found for the given identifier' }
```

[CODE / GIST](https://gist.github.com/notJackson/227bedcd2df4cdd55200c39d0df1c129)

What I've tried:
*) Swapping servers(ips, locations) (multiple times..)

Looks like to me [steam openid](https://steamcommunity.com/dev) is fucking up, but how come I'm the only one affected by this.

Using
 openid@2.0.1

**Comment by havard** [comment]
The Steam OpenID provider seems rather unstable. I don't know why you're experiencing these issues, but try logging the responses you receive from Steam in the cases where it fails and see what that tells you.
