### ISSUE TITLE
Authenticating against Yahoo OpenID fails

### ISSUE THREAD

**Issue by AGT89** [havard/node-openid#163]
As explained in jaredhanson/passport-yahoo#6, authenticating against Yahoo with OpenID started failing a few weeks ago. The issue appears to be caused by the Accept header sent by this module.

Either removing the "\*/\*" or reducing the quality of the "\*/\*" (e.g. to "\*/\*;q=0.9") in the Accept header seem to fix the issue.

**Comment by havard** [comment]
Thanks for reporting this. Fixed in 2.0.6 and backported to 1.0.4.
