### ISSUE TITLE
Can you breify explain what these fields are? I trying to figure out open id, but am a super noob

### ISSUE THREAD

**Issue by kevinlbatchelor** [havard/node-openid#167]
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '?openid_identifier=test',
  query: 'openid_identifier=test',
  pathname: '/authenticate',
  path: '/authenticate?openid_identifier=test',
  href: '/authenticate?openid_identifier=test' }

**Comment by havard** [comment]
They are parts of a parsed URL, seemingly. I'd recommend reading up on Node and its url library.
