### ISSUE TITLE
Multiple URI parameters are NOT considered ('No valid providers were discovered for the asserted claimed identifier)

### ISSUE THREAD

**Issue by soorur** [havard/node-openid#171]
Standard: http://wiki.openid.net/w/page/12995256/XRD-based%20Service%20Discovery#URI

Our provider:

![image](https://user-images.githubusercontent.com/12500468/55069192-251fdf00-508c-11e9-87ab-e02e1f740bf4.png)

When using the first endpoint everything works, but when using the second one, then it fails with a message:

No valid providers were discovered for the asserted claimed identifier.

Any hopes for a fix? :D

**Comment by jooseplall** [comment]
Opened a pull request with possible solution: https://github.com/havard/node-openid/pull/172/files
@havard can maybe review and merge?

**Comment by havard** [comment]
I may be missing something here, but given three unprioritized URIs we should be able to just choose the first and be done with it? Could you please explain a bit further why your suggested change is correct and/or useful?

**Comment by havard** [comment]
I know it has been almost a year, but could you please respond with a clarification @jooseplall?

**Comment by havard** [comment]
Closing this since the referenced spec at http://wiki.openid.net/w/page/12995256/XRD-based%20Service%20Discovery#URI dictates that if several elements share priority, one should be chosen at random. (We choose the first, but that is not a breach.)
