### ISSUE TITLE
Zero byte on default prime

### ISSUE THREAD

**Issue by emilbayes** [havard/node-openid#173]
Hi!

Reviewing the code I found that the base64 encoding of the default prime is prefixed by a zero byte that is not specified in the openid auth 2.0 spec. I figured that this did not cause any issues if the prime is big endian encoded, but wanted to open an issue nevertheless.

Current encoding:

```js
Buffer.from('ANz5OguIOXLsDhmYmsWizjEOHTdxfo2Vcbt2I3MYZuYe91ouJ4mLBX+YkcLiemOcPym2CBRYHNOyyjmG0mg3BVd9RcLn5S3IHHoXGHblzqdLFEi/368Ygo79JRnxTkXjgmY0rxlJ5bU1zIKaSDuKdiI+XUkKJX8Fvf8W8vsixYOr', 'base64').toString('hex') === '00dcf93a0b883972ec0e19989ac5a2ce310e1d37717e8d9571bb7623731866e61ef75a2e27898b057f9891c2e27a639c3f29b60814581cd3b2ca3986d2683705577d45c2e7e52dc81c7a171876e5cea74b1448bfdfaf18828efd2519f14e45e3826634af1949e5b535cc829a483b8a76223e5d490a257f05bdff16f2fb22c583ab'
```

Spec encoding:

```js
Buffer.from('DCF93A0B883972EC0E19989AC5A2CE310E1D37717E8D9571BB7623731866E61EF75A2E27898B057F9891C2E27A639C3F29B60814581CD3B2CA3986D2683705577D45C2E7E52DC81C7A171876E5CEA74B1448BFDFAF18828EFD2519F14E45E3826634AF1949E5B535CC829A483B8A76223E5D490A257F05BDFF16F2FB22C583AB', 'hex').toString('base64') === '3Pk6C4g5cuwOGZiaxaLOMQ4dN3F+jZVxu3Yjcxhm5h73Wi4niYsFf5iRwuJ6Y5w/KbYIFFgc07LKOYbSaDcFV31FwuflLcgcehcYduXOp0sUSL/frxiCjv0lGfFOReOCZjSvGUnltTXMgppIO4p2Ij5dSQolfwW9/xby+yLFg6s='
```

Maybe there's a reason I'm not seeing, but I didn't find it mentioned in the source or any other issues

**Comment by emilbayes** [comment]
Ah I guess this is the reason why: https://security.stackexchange.com/a/40059

**Comment by havard** [comment]
Yes, the reason for this lies within the use of openssl in Node and avoiding interpretation problems. I fail to see how this is a breach from the spec, could you please refer me to the source which made you conclude this?

**Comment by emilbayes** [comment]
It was this part https://openid.net/specs/openid-authentication-2_0.html#pvalue, but I presume they left out "implementation details" like OpenSSL's requirement of a zero byte prefix if the first bit of the first byte is high.

**Comment by havard** [comment]
Closing this since we seem to have a common understanding that this is actually OK. Feel free to reopen if my conclusion is wrong.
