### ISSUE TITLE
Please update dependencies (request module), due to vulnerability

### ISSUE THREAD

**Issue by ZissisT** [havard/node-openid#175]
Hello,

Right now this depends on request@^2.61.0 which has a memory leak vulnerability
(https://github.com/request/request/issues/2938 )

Can this be updated to newer request version?

Thank you

**Comment by havard** [comment]
Sorry for the delayed response. 2.0.7 has been published and depends on request 2.88.2 (latest version as of today). Since request is deprecated, I will look into removing the dependency on it.
